### PR TITLE
Add user posts

### PR DESCRIPTION
**Pull request by hoangvvo**
This adds a user posting system, like status update, tweeting, etc.

### CODE REVIEW

**Comment by hoangvvo** [comment]
`swr` really has awful documentation...

**Comment by hoangvvo** [comment]
I'm currently not know how to reset `useSWRPages` (which is not even in the documentation :dizzy_face:) state

**Comment by wortkotze** [comment]
> I'm currently not know how to reset `useSWRPages` (which is not even in the documentation 😵) state

for which usecase do you need an reset?
probably this helps:
https://sergiodxa.com/articles/swr/pagination/

**Comment by hoangvvo** [comment]
@wortkotze When a user make a post, I want it to appear immediately under the feed. I tried [@shuding's workaround](https://github.com/zeit/swr/issues/189#issuecomment-565474456) but it didn't work somehow.

Take a look at https://github.com/zeit/swr/issues/189

**Comment by hoangvvo** [comment]
The article you mention is pretty interesting though. I would love to implement an infinity scrolled pagination (right now we need to press a button)

**Comment by wortkotze** [comment]
> The article you mention is pretty interesting though. I would love to implement an infinity scrolled pagination (right now we need to press a button)

I'm not sure but you could use the mutation of the swr
https://github.com/zeit/swr#mutation-and-post-request

with mutate you can change the api-url of swr or the load. in this way you could change the data that you are requesting

**Comment by hoangvvo** [comment]
> > The article you mention is pretty interesting though. I would love to implement an infinity scrolled pagination (right now we need to press a button)
> 
> I'm not sure but you could use the mutation of the swr
> https://github.com/zeit/swr#mutation-and-post-request
> 
> with mutate you can change the api-url of swr or the load. in this way you could change the data that you are requesting

I did try that but somehow did not manage to get it to work. I tried to use mutate on `swrPages[0]` (the first in all paginations) but somehow it didn't work

**Comment by hoangvvo** [comment]
I'll merge it for now. Will also post an issue to keep track of this.

**Pull request merged**
